import React, { type JSX } from "react";
import "@xyflow/react/dist/style.css";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Box, CheckCircle2, ChevronRight, CircleAlert, Clock3, Code2, Copy, Cpu, FileArchive, GitBranch, Layers3, LoaderCircle, Network, RefreshCw, Search, ShieldCheck, Wrench, XCircle } from "lucide-react";
import { api, subscribeToEvents } from "./lib/api";
import { formatDate, formatNumber, formatRelative } from "./lib/format";
import { Badge, Button, Card, CardBody, CardHeader, CopyableId, EmptyState, ErrorState, Label, Skeleton, StatusBadge } from "./components/ui";
import type { AgentDetailDto, AgentSummaryDto, ArtifactDetailDto, ArtifactSummaryDto, OperationsDto, PtcExecutionDetailDto, PtcExecutionSummaryDto, RuntimeMetricsDto, TaskDetailDto, TaskGraphDto, TaskSummaryDto, ToolSummaryDto } from "@mnemos/contracts";

export function ArtifactsPage(): JSX.Element {
  const [draft, setDraft] = React.useState(""); const [query, setQuery] = React.useState(""); const [selectedId, setSelectedId] = React.useState<string | null>(null); const [range, setRange] = React.useState(0);
  const page = useQuery({ queryKey: ["artifacts", query], queryFn: () => api.artifacts({ query, limit: 50 }) }); const detail = useQuery({ queryKey: ["artifact", selectedId, range], queryFn: () => api.artifact(selectedId!, { offset: range, length: 16_384 }), enabled: Boolean(selectedId) });
  return <div className="space-y-6"><PageIntro eyebrow="Runtime / artifacts" title="Inspect externalized work without loading it all." detail="Artifact metadata, bounded previews, range reads, and query matches stay behind the runtime boundary." /><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_460px]"><Card><CardHeader><form className="flex flex-wrap gap-2" onSubmit={(event) => { event.preventDefault(); setQuery(draft.trim()); }}><label htmlFor="artifact-search" className="sr-only">Search artifacts</label><input id="artifact-search" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Search type, id, summary…" className="h-10 min-w-[220px] flex-1 rounded-md border border-line bg-canvas px-3 text-sm outline-none focus:border-amber-400" /><Button type="submit"><Search size={15} />Search</Button></form></CardHeader><CardBody className="p-0">{page.isLoading ? <ListSkeleton /> : page.isError ? <div className="p-5"><ErrorState message="Artifact index unavailable." onRetry={() => void page.refetch()} /></div> : page.data?.items.length ? <div className="divide-y divide-line">{page.data.items.map((artifact) => <ArtifactRow key={artifact.id} artifact={artifact} selected={artifact.id === selectedId} onSelect={() => { setSelectedId(artifact.id); setRange(0); }} />)}</div> : <div className="p-8"><EmptyState title="No artifacts" detail="Completed tool and PTC workflows will appear here." /></div>}</CardBody></Card><ArtifactDetail detail={detail.data} loading={detail.isLoading} range={range} onRange={setRange} /></div></div>;
}

export function ToolsPage(): JSX.Element {
  const [draft, setDraft] = React.useState(""); const [query, setQuery] = React.useState(""); const [loaded, setLoaded] = React.useState(false); const [selected, setSelected] = React.useState<ToolSummaryDto | null>(null); const page = useQuery({ queryKey: ["tools", query, loaded], queryFn: () => api.tools({ query, loaded: loaded || undefined, limit: 100 }) });
  return <div className="space-y-6"><PageIntro eyebrow="Runtime / tools" title="One catalog, two execution paths." detail="Native calls and PTC SDK calls share the same definitions, permissions, side-effect metadata, and dispatcher authority." /><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]"><Card><CardHeader><div className="flex flex-wrap gap-2"><form className="flex min-w-[240px] flex-1 gap-2" onSubmit={(event) => { event.preventDefault(); setQuery(draft.trim()); }}><label htmlFor="tool-search" className="sr-only">Search tools</label><input id="tool-search" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Search tool or namespace…" className="h-10 min-w-0 flex-1 rounded-md border border-line bg-canvas px-3 text-sm outline-none focus:border-amber-400" /><Button type="submit"><Search size={15} />Search</Button></form><Button variant={loaded ? "default" : "outline"} onClick={() => setLoaded(!loaded)}>{loaded ? "Loaded only" : "All tools"}</Button></div></CardHeader><CardBody className="p-0"><div className="divide-y divide-line">{page.data?.items.map((tool) => <button type="button" key={tool.name} onClick={() => setSelected(tool)} className={`flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-ink/[0.025] ${selected?.name === tool.name ? "bg-amber-400/10" : ""}`}><span className={`grid h-8 w-8 place-items-center rounded-md ${tool.sideEffect === "read" ? "bg-emerald-400/15 text-emerald-700" : "bg-amber-400/15 text-amber-700"}`}><Wrench size={15} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{tool.name}</span><span className="mt-1 block text-xs text-ink-muted">{tool.namespace} · {tool.schemaTokens} schema tokens</span></span><Badge tone={tool.loaded ? "success" : "neutral"}>{tool.loaded ? "loaded" : "available"}</Badge></button>)}{!page.data?.items.length ? <div className="p-8"><EmptyState title="No matching tools" detail="Try a broader catalog query." /></div> : null}</div></CardBody></Card><ToolDetail tool={selected} /></div><PtcSummaryLink /></div>;
}

export function PtcPage(): JSX.Element { const [selectedId, setSelectedId] = React.useState<string | null>(null); const page = useQuery({ queryKey: ["ptc"], queryFn: api.ptc }); const detail = useQuery({ queryKey: ["ptc-detail", selectedId], queryFn: () => api.ptcExecution(selectedId!), enabled: Boolean(selectedId) }); return <div className="space-y-6"><PageIntro eyebrow="Runtime / PTC" title="Programmatic calls, without private reasoning." detail="This timeline shows bounded scheduler metadata: parallel reads, barriers, tool calls, quotas, and artifact spills." /><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_520px]"><Card><CardHeader><div className="flex items-center justify-between"><div><Label>Executions</Label><h2 className="mt-1 text-lg font-semibold">Recent PTC runs</h2></div><Badge tone="neutral">{page.data?.total ?? 0} total</Badge></div></CardHeader><CardBody className="p-0">{page.isLoading ? <ListSkeleton /> : page.data?.items.map((execution) => <PtcRow key={execution.id} execution={execution} selected={execution.id === selectedId} onSelect={() => setSelectedId(execution.id)} />)}{!page.data?.items.length ? <div className="p-8"><EmptyState title="No PTC executions" detail="Run a multi-step workflow to see scheduler activity." /></div> : null}</CardBody></Card><PtcDetail detail={detail.data} loading={detail.isLoading} /></div></div>; }

export function AgentsPage(): JSX.Element { const page = useQuery({ queryKey: ["agents"], queryFn: api.agents }); const [selected, setSelected] = React.useState<string | null>(null); const detail = useQuery({ queryKey: ["agent", selected], queryFn: () => api.agent(selected!), enabled: Boolean(selected) }); useRuntimeInvalidation(["agents", "tasks", "metrics"]); return <div className="space-y-6"><PageIntro eyebrow="Runtime / agents" title="Bounded reasoning actors." detail="Roles, providers, permissions, budgets, and context limits are runtime-owned; the Console only exposes safe summaries." /><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]"><Card><CardBody className="p-0 divide-y divide-line">{page.data?.items.map((agent) => <AgentRow key={agent.id} agent={agent} selected={selected === agent.id} onSelect={() => setSelected(agent.id)} />)}{!page.data?.items.length ? <div className="p-8"><EmptyState title="No agents" detail="Register an agent definition to inspect it." /></div> : null}</CardBody></Card><AgentDetail detail={detail.data} /></div></div>; }

export function TasksPage(): JSX.Element { const tasks = useQuery({ queryKey: ["tasks"], queryFn: api.tasks }); const graph = useQuery({ queryKey: ["task-graph"], queryFn: () => api.taskGraph() }); const [selected, setSelected] = React.useState<string | null>(null); const detail = useQuery({ queryKey: ["task", selected], queryFn: () => api.task(selected!), enabled: Boolean(selected) }); useRuntimeInvalidation(["tasks", "task-graph", "agents", "metrics"]); return <div className="space-y-6"><PageIntro eyebrow="Runtime / tasks" title="See delegation as a graph, not a transcript." detail="Task dependencies, handoffs, review loops, and durable statuses are visible without copying private agent context." /><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]"><Card><CardHeader><div className="flex items-center justify-between"><div><Label>Task graph</Label><h2 className="mt-1 text-lg font-semibold">Bounded orchestration workspace</h2></div><Badge tone="neutral">{graph.data?.nodes.length ?? 0} nodes</Badge></div></CardHeader><CardBody>{graph.isLoading ? <Skeleton className="h-[430px]" /> : graph.data ? <TaskGraph graph={graph.data} onSelect={setSelected} /> : <EmptyState title="Graph unavailable" detail="The runtime did not return a task graph." />}</CardBody></Card><TaskDetail detail={detail.data} /></div><Card><CardHeader><Label>Task ledger</Label></CardHeader><CardBody className="p-0 divide-y divide-line">{tasks.data?.items.map((task) => <button type="button" key={task.id} onClick={() => setSelected(task.id)} className="flex w-full items-center gap-3 px-5 py-3 text-left hover:bg-ink/[0.025]"><StatusBadge status={task.status} /><span className="min-w-0 flex-1 truncate text-sm font-semibold">{task.objective}</span><CopyableId value={task.id} /></button>)}</CardBody></Card></div>; }

export function DashboardPage(): JSX.Element { const summary = useQuery({ queryKey: ["summary"], queryFn: api.summary, refetchInterval: 15_000 }); const metrics = useQuery({ queryKey: ["metrics"], queryFn: api.metrics, refetchInterval: 10_000 }); const operations = useQuery({ queryKey: ["operations"], queryFn: api.operations, refetchInterval: 15_000 }); useRuntimeInvalidation(["metrics", "operations", "summary"]); return <div className="space-y-6"><PageIntro eyebrow="Runtime / dashboard" title="A live view of your cognitive runtime." detail="Operational counters and bounded trends come from the runtime adapter. Missing telemetry is shown as N/A, never guessed." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Runtime status" value={operations.data?.readiness.status ?? "N/A"} detail={summary.data?.profile ?? "runtime"} tone={operations.data?.readiness.status === "ok" ? "good" : "warn"} /><Stat label="Sessions" value={formatNumber(summary.data?.sessionsCount)} detail={`${formatNumber(summary.data?.activeSessions)} active`} /><Stat label="Agents / tasks" value={`${formatNumber(metrics.data?.activeAgents)} / ${formatNumber(metrics.data?.activeTasks)}`} detail="currently running" /><Stat label="Memory / artifacts" value={`${formatNumber(summary.data?.memoryCount)} / ${formatNumber(summary.data?.artifactCount)}`} detail="derived + externalized" /></div><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><Card><CardHeader><div className="flex items-center justify-between"><div><Label>Signals</Label><h2 className="mt-1 text-lg font-semibold">Requests, pressure, queue</h2></div><Badge tone="neutral">last 60 samples</Badge></div></CardHeader><CardBody>{metrics.isLoading ? <Skeleton className="h-64" /> : metrics.data ? <MetricsChart metrics={metrics.data} /> : <EmptyState title="Metrics unavailable" detail="The runtime did not expose time series data." />}</CardBody></Card><OperationsSummary operations={operations.data} /></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Tool calls" value={formatNumber(metrics.data?.toolCalls)} detail={`${formatNumber(metrics.data?.ptcExecutions)} PTC`} /><Stat label="Queue depth" value={formatNumber(metrics.data?.queueDepth)} detail={`${formatNumber(metrics.data?.activeWorkers)} worker`} /><Stat label="Context pressure" value={metrics.data ? `${Math.round(metrics.data.contextPressure * 100)}%` : "N/A"} detail="visible runtime" /><Stat label="Sandbox" value={operations.data?.sandbox.status ?? "N/A"} detail={operations.data?.sandbox.backend ?? "not reported"} /></div></div>; }

export function OperationsPage(): JSX.Element { const query = useQuery({ queryKey: ["operations"], queryFn: api.operations, refetchInterval: 15_000 }); const operations = query.data; return <div className="space-y-6"><PageIntro eyebrow="Runtime / operations" title="Readiness, workers, storage, and sandbox boundaries." detail="This is a read-only operator view. It never exposes secrets, database paths, prompts, or private reasoning." />{query.isError ? <ErrorState message="Operational diagnostics unavailable." onRetry={() => void query.refetch()} /> : null}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><OperationCard title="Health / readiness" icon={<ShieldCheck size={16} />}><Definition label="Liveness" value={operations?.health.status ?? "N/A"} /><Definition label="Readiness" value={operations?.readiness.status ?? "N/A"} />{operations?.readiness.checks.map((check) => <div key={check.name} className="mt-2 flex items-center justify-between text-xs"><span>{check.name}</span><Badge tone={check.ok ? "success" : "danger"}>{check.ok ? "ok" : "failed"}</Badge></div>)}</OperationCard><OperationCard title="Workers / jobs" icon={<Cpu size={16} />}><Definition label="Workers" value={operations?.workers.length ?? "N/A"} /><Definition label="Jobs" value={operations?.jobs.length ?? "N/A"} />{operations?.workers.map((worker) => <div key={worker.id} className="mt-2 flex items-center justify-between text-xs"><span>{worker.id}</span><StatusBadge status={worker.status} /></div>)}</OperationCard><OperationCard title="Storage" icon={<DatabaseIcon />}><Definition label="Memory records" value={operations?.storage.memoryCount ?? "N/A"} /><Definition label="Artifacts" value={operations?.storage.artifactCount ?? "N/A"} /><Definition label="Audit retention" value={operations?.audit.retention ?? "N/A"} /></OperationCard><OperationCard title="Migrations" icon={<Layers3 size={16} />}><Definition label="Schema" value={operations ? `v${operations.migrations.schemaVersion}` : "N/A"} /><Definition label="Pending" value={operations?.migrations.pending ?? "N/A"} /></OperationCard><OperationCard title="Sandbox" icon={<ShieldCheck size={16} />}><Definition label="Backend" value={operations?.sandbox.backend ?? "N/A"} /><Definition label="Status" value={operations?.sandbox.status ?? "N/A"} /><div className="mt-3 flex flex-wrap gap-1">{operations?.sandbox.capabilities.map((capability) => <Badge key={capability}>{capability}</Badge>)}</div></OperationCard><OperationCard title="Provider / audit" icon={<Activity size={16} />}><Definition label="Provider" value={operations?.provider.status ?? "N/A"} /><Definition label="Audit rows" value={operations?.audit.rows ?? "N/A"} /><p className="mt-2 text-xs text-ink-muted">{operations?.provider.names.join(", ") || "No provider names reported"}</p></OperationCard></div></div>; }

function ArtifactRow({ artifact, selected, onSelect }: { artifact: ArtifactSummaryDto; selected: boolean; onSelect: () => void }): JSX.Element { return <button type="button" onClick={onSelect} className={`flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-ink/[0.025] ${selected ? "bg-amber-400/10" : ""}`}><span className="grid h-8 w-8 place-items-center rounded-md bg-amber-400/15 text-amber-700"><FileArchive size={15} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{artifact.summary ?? artifact.type}</span><span className="mt-1 block text-xs text-ink-muted">{artifact.mimeType ?? "binary"} · {formatBytes(artifact.sizeBytes)} · {formatRelative(artifact.updatedAt)}</span></span><CopyableId value={artifact.id} /></button>; }
function ArtifactDetail({ detail, loading, range, onRange }: { detail?: ArtifactDetailDto; loading: boolean; range: number; onRange: (value: number) => void }): JSX.Element { return <Card><CardHeader><Label>Artifact detail</Label><h2 className="mt-1 text-lg font-semibold">{detail?.type ?? "Select an artifact"}</h2></CardHeader><CardBody>{loading ? <Skeleton className="h-64" /> : detail ? <div className="space-y-4"><div className="grid grid-cols-2 gap-3 text-xs"><Definition label="Size" value={formatBytes(detail.sizeBytes)} /><Definition label="Checksum" value={detail.checksum ?? "N/A"} /><Definition label="Created by" value={detail.createdBy ?? "N/A"} /><Definition label="Scope" value={detail.scope} /></div><div className="flex items-center justify-between"><Label>Bounded range</Label><div className="flex gap-1"><Button variant="quiet" disabled={range === 0} onClick={() => onRange(Math.max(0, range - 512))}>←</Button><Button variant="quiet" onClick={() => onRange(range + 512)}>→</Button></div></div><pre className="max-h-72 overflow-auto rounded-lg bg-canvas p-3 font-mono text-xs leading-5">{detail.range?.content ?? detail.preview?.content ?? "No preview available."}</pre><p className="text-[11px] text-ink-muted">{detail.range?.truncated ? "Preview truncated; use range reads or query matches." : "Preview is bounded by the server contract."}</p></div> : <EmptyState title="Choose an artifact" detail="Only metadata and bounded body slices are loaded." />}</CardBody></Card>; }
function ToolDetail({ tool }: { tool: ToolSummaryDto | null }): JSX.Element { return <Card><CardHeader><Label>Tool contract</Label><h2 className="mt-1 text-lg font-semibold">{tool?.name ?? "Select a tool"}</h2></CardHeader><CardBody>{tool ? <div className="space-y-4"><p className="text-sm leading-6">{tool.description}</p><div className="grid grid-cols-2 gap-3 text-xs"><Definition label="Namespace" value={tool.namespace} /><Definition label="Side effect" value={tool.sideEffect} /><Definition label="Concurrency" value={tool.concurrencySafe ? "safe" : "barrier"} /><Definition label="Schema tokens" value={tool.schemaTokens} /></div><div><Label>Permissions</Label><div className="mt-2 flex flex-wrap gap-1">{tool.permissions.map((permission) => <Badge key={permission}>{permission}</Badge>)}</div></div><pre className="max-h-56 overflow-auto rounded-lg bg-canvas p-3 font-mono text-[11px]">{JSON.stringify(tool.schema, null, 2)}</pre></div> : <EmptyState title="Choose a tool" detail="Native and PTC use this same contract." />}</CardBody></Card>; }
function PtcRow({ execution, selected, onSelect }: { execution: PtcExecutionSummaryDto; selected: boolean; onSelect: () => void }): JSX.Element { return <button type="button" onClick={onSelect} className={`flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-ink/[0.025] ${selected ? "bg-amber-400/10" : ""}`}><span className="grid h-8 w-8 place-items-center rounded-md bg-purple-400/15 text-purple-700"><Code2 size={15} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{execution.id}</span><span className="mt-1 block text-xs text-ink-muted">{execution.toolCalls} calls · peak {execution.peakConcurrency} · {execution.durationMs}ms</span></span><StatusBadge status={execution.status} /></button>; }
function PtcDetail({ detail, loading }: { detail?: PtcExecutionDetailDto; loading: boolean }): JSX.Element { return <Card><CardHeader><Label>PTC timeline</Label><h2 className="mt-1 text-lg font-semibold">{detail?.id ?? "Select an execution"}</h2></CardHeader><CardBody>{loading ? <Skeleton className="h-64" /> : detail ? <div className="space-y-4"><div className="grid grid-cols-2 gap-3 text-xs"><Definition label="Status" value={detail.status} /><Definition label="Duration" value={`${detail.durationMs} ms`} /><Definition label="Calls" value={`${detail.quotaUsed}/${detail.quotaLimit}`} /><Definition label="Peak concurrency" value={detail.peakConcurrency} /><Definition label="Spills" value={detail.artifactSpills} /><Definition label="Final" value={detail.finalResultKind ?? "none"} /></div><div className="space-y-2 border-l border-line pl-4">{detail.timeline.map((event) => <div key={event.id} className="relative text-xs"><span className="absolute -left-[21px] top-1 h-2 w-2 rounded-full bg-amber-400" /><div className="flex items-center justify-between gap-3"><span className="font-semibold">{event.label}</span><span className="font-mono text-ink-muted">{event.atMs}ms</span></div><p className="mt-1 text-ink-muted">{event.kind}{event.toolName ? ` · ${event.toolName}` : ""}{event.concurrency ? ` · concurrency ${event.concurrency}` : ""}</p></div>)}</div><pre className="rounded-lg bg-canvas p-3 font-mono text-[11px]">{detail.codePreview ?? "No program preview"}</pre></div> : <EmptyState title="Choose an execution" detail="The scheduler timeline omits private program reasoning." />}</CardBody></Card>; }
function AgentRow({ agent, selected, onSelect }: { agent: AgentSummaryDto; selected: boolean; onSelect: () => void }): JSX.Element { return <button type="button" onClick={onSelect} className={`flex w-full items-center gap-3 px-5 py-4 text-left hover:bg-ink/[0.025] ${selected ? "bg-amber-400/10" : ""}`}><span className="grid h-8 w-8 place-items-center rounded-md bg-sky-400/15 text-sky-700"><Network size={15} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{agent.name}</span><span className="mt-1 block text-xs text-ink-muted">{agent.role} · {agent.modelProfile} · {agent.toolCount} tools</span></span><StatusBadge status={agent.status} /></button>; }
function AgentDetail({ detail }: { detail?: AgentDetailDto }): JSX.Element { return <Card><CardHeader><Label>Agent detail</Label><h2 className="mt-1 text-lg font-semibold">{detail?.name ?? "Select an agent"}</h2></CardHeader><CardBody>{detail ? <div className="space-y-4"><p className="text-sm leading-6">{detail.objective}</p><div className="grid grid-cols-2 gap-3 text-xs"><Definition label="Role" value={detail.role} /><Definition label="Model" value={detail.modelProfile} /><Definition label="Context" value={`${Math.round(detail.contextLimitTokens / 1024)}k`} /><Definition label="Tokens used" value={formatNumber(detail.tokensUsed)} /><Definition label="Depth" value={detail.delegationDepth} /><Definition label="Retries" value={detail.retryCount} /></div><div><Label>Permissions</Label><div className="mt-2 flex flex-wrap gap-1">{detail.permissions.map((permission) => <Badge key={permission}>{permission}</Badge>)}</div></div><div><Label>Loaded tools</Label><p className="mt-2 text-xs text-ink-muted">{detail.loadedToolNames.join(" · ")}</p></div></div> : <EmptyState title="Choose an agent" detail="Role, budget, tools, and safe context metadata appear here." />}</CardBody></Card>; }
function TaskDetail({ detail }: { detail?: TaskDetailDto }): JSX.Element { return <Card><CardHeader><Label>Task detail</Label><h2 className="mt-1 text-lg font-semibold">{detail?.objective ?? "Select a task"}</h2></CardHeader><CardBody>{detail ? <div className="space-y-4"><div className="flex items-center gap-2"><StatusBadge status={detail.status} /><CopyableId value={detail.id} /></div><div className="grid grid-cols-2 gap-3 text-xs"><Definition label="Assigned" value={detail.assignedAgentId ?? "unassigned"} /><Definition label="Dependencies" value={detail.dependencyIds.length} /><Definition label="Retries" value={detail.retryCount} /><Definition label="Review loop" value={detail.reviewIteration} /></div><p className="rounded-lg bg-canvas p-3 text-xs leading-5">{detail.outputPreview ?? detail.localSummary ?? "No output summary yet."}</p><div><Label>References</Label><div className="mt-2 flex flex-wrap gap-1">{detail.outputRefs.map((ref) => <Badge key={ref}>{ref}</Badge>)}</div></div></div> : <EmptyState title="Choose a task" detail="The graph stays bounded; full payloads remain in ArtifactStore." />}</CardBody></Card>; }
const ReactFlowCanvas = React.lazy(async () => {
  const mod = await import("@xyflow/react");
  const Component = ({ graph, onSelect }: { graph: TaskGraphDto; onSelect: (id: string) => void }): JSX.Element => {
    const nodes = graph.nodes.map((node) => ({
      id: node.id,
      position: node.position,
      data: { label: <button type="button" className="w-full text-left" onClick={() => onSelect(node.taskId ?? node.id)}><div className="flex items-center justify-between gap-2"><span className="max-w-[130px] truncate text-xs font-semibold">{node.label}</span><span className="text-[10px] text-ink-muted">{node.status}</span></div><div className="mt-1 text-[10px] text-ink-muted">{node.role ?? "task"}</div></button> },
      type: "default" as const,
    }));
    const edges = graph.edges.map((edge) => ({ id: edge.id, source: edge.source, target: edge.target, label: edge.kind, animated: edge.kind === "handoff" }));
    return <div className="h-[430px] min-w-[620px] overflow-hidden rounded-lg bg-canvas"><mod.ReactFlow nodes={nodes} edges={edges} fitView nodesDraggable={false} nodesConnectable={false} proOptions={{ hideAttribution: true }}><mod.Background gap={20} size={1} /><mod.Controls /><mod.MiniMap pannable zoomable /></mod.ReactFlow></div>;
  };
  return { default: Component };
});
function TaskGraph({ graph, onSelect }: { graph: TaskGraphDto; onSelect: (id: string) => void }): JSX.Element { return <React.Suspense fallback={<Skeleton className="h-[430px]" />}><ReactFlowCanvas graph={graph} onSelect={onSelect} /></React.Suspense>; }
function MetricsChart({ metrics }: { metrics: RuntimeMetricsDto }): JSX.Element { const Chart = React.lazy(async () => { const mod = await import("recharts"); return { default: ({ data }: { data: { at: string; requests: number; pressure: number; queue: number }[] }) => <mod.ResponsiveContainer width="100%" height={260}><mod.LineChart data={data}><mod.CartesianGrid strokeDasharray="3 3" stroke="currentColor" opacity={0.12} /><mod.XAxis dataKey="at" tickFormatter={(value: string) => value.slice(11, 16)} fontSize={10} /><mod.YAxis yAxisId="left" fontSize={10} /><mod.YAxis yAxisId="right" orientation="right" domain={[0, 1]} fontSize={10} /><mod.Tooltip /><mod.Line yAxisId="left" type="monotone" dataKey="requests" stroke="#d99838" strokeWidth={2} dot={false} /><mod.Line yAxisId="right" type="monotone" dataKey="pressure" stroke="#4f8f88" strokeWidth={2} dot={false} /><mod.Line yAxisId="left" type="monotone" dataKey="queue" stroke="#8b6fb0" strokeWidth={2} dot={false} /></mod.LineChart></mod.ResponsiveContainer> }; }); const data = metrics.series.requests.map((point, index) => ({ at: point.at, requests: point.value, pressure: metrics.series.pressure[index]?.value ?? metrics.contextPressure, queue: metrics.series.queue[index]?.value ?? metrics.queueDepth })); return <React.Suspense fallback={<Skeleton className="h-64" />}><Chart data={data} /></React.Suspense>; }
function OperationsSummary({ operations }: { operations?: OperationsDto }): JSX.Element { return <Card><CardHeader><Label>Operational pulse</Label><h2 className="mt-1 text-lg font-semibold">Read-only checks</h2></CardHeader><CardBody className="space-y-3">{operations ? <>{operations.readiness.checks.slice(0, 5).map((check) => <div key={check.name} className="flex items-center justify-between text-xs"><span>{check.name}</span><span className="flex items-center gap-1">{check.ok ? <CheckCircle2 className="text-emerald-600" size={14} /> : <CircleAlert className="text-amber-600" size={14} />}{check.ok ? "ok" : "attention"}</span></div>)}<a href="/operations" className="inline-flex items-center gap-1 text-xs font-semibold text-amber-700">Open operations <ChevronRight size={13} /></a></> : <Skeleton className="h-32" />}</CardBody></Card>; }
function OperationCard({ title, icon, children }: { title: string; icon: JSX.Element; children: React.ReactNode }): JSX.Element { return <Card><CardHeader><div className="flex items-center gap-2"><span className="text-amber-700">{icon}</span><h2 className="text-sm font-semibold">{title}</h2></div></CardHeader><CardBody>{children}</CardBody></Card>; }
function Stat({ label, value, detail, tone = "neutral" }: { label: string; value: string; detail: string; tone?: "neutral" | "good" | "warn" }): JSX.Element { return <Card><CardBody className="relative"><div className={`absolute inset-x-0 top-0 h-0.5 ${tone === "good" ? "bg-emerald-400" : tone === "warn" ? "bg-amber-400" : "bg-ink/10 dark:bg-white/15"}`} /><Label>{label}</Label><p className="mt-3 truncate text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-ink-muted">{detail}</p></CardBody></Card>; }
function PageIntro({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: React.ReactNode }): JSX.Element { return <div className="max-w-3xl"><Label>{eyebrow}</Label><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-muted sm:text-base">{detail}</p></div>; }
function Definition({ label, value }: { label: string; value: React.ReactNode }): JSX.Element { return <div><dt className="text-xs text-ink-muted">{label}</dt><dd className="mt-1 truncate text-sm font-semibold">{value}</dd></div>; }
function ListSkeleton(): JSX.Element { return <div className="space-y-3 p-5"><Skeleton className="h-14" /><Skeleton className="h-14" /><Skeleton className="h-14" /></div>; }
function formatBytes(bytes: number): string { if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`; return `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function DatabaseIcon(): JSX.Element { return <Box size={16} />; }
function PtcSummaryLink(): JSX.Element { return <a href="/ptc" className="inline-flex items-center gap-1 text-sm font-semibold text-amber-700">Open PTC execution inspector <ChevronRight size={14} /></a>; }
function useRuntimeInvalidation(keys: string[]): void { const queryClient = useQueryClient(); React.useEffect(() => subscribeToEvents((event) => { if (event.type.startsWith("task.") || event.type.startsWith("agent.") || event.type.startsWith("ptc.")) for (const key of keys) void queryClient.invalidateQueries({ queryKey: [key] }); }, () => undefined), [queryClient, keys.join("|")]); }
