import React, { type JSX } from "react";
import { createRootRoute, createRoute, createRouter, Link, Outlet, useNavigate, useParams } from "@tanstack/react-router";
import { Activity, ArrowLeft, ChevronRight, CircleHelp, Cpu, Database, ExternalLink, LayoutDashboard, Menu, Moon, PanelLeft, Radio, Search, Settings, Sun, X } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { api, ApiClientError, subscribeToEvents } from "./lib/api";
import { formatDate, formatNumber, formatRelative, shortId } from "./lib/format";
import { useUiStore, type ThemePreference } from "./lib/ui-store";
import { Badge, Button, Card, CardBody, CardHeader, CopyableId, EmptyState, ErrorState, Label, Skeleton, StatusBadge, StatusDot } from "./components/ui";
import type { RuntimeEventDto } from "@mnemos/contracts";

const rootRoute = createRootRoute({ component: AppShell, notFoundComponent: NotFoundPage });
const overviewRoute = createRoute({ getParentRoute: () => rootRoute, path: "/", component: OverviewPage });
const sessionsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/sessions", component: SessionsPage });
const sessionRoute = createRoute({ getParentRoute: () => rootRoute, path: "/sessions/$sessionId", component: SessionPage });
const eventsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/events", component: EventsPage });
const settingsRoute = createRoute({ getParentRoute: () => rootRoute, path: "/settings", component: SettingsPage });
const routeTree = rootRoute.addChildren([overviewRoute, sessionsRoute, sessionRoute, eventsRoute, settingsRoute]);
export const router = createRouter({ routeTree, defaultPreload: "intent" });
declare module "@tanstack/react-router" { interface Register { router: typeof router; } }

export function AppShell(): JSX.Element {
  const collapsed = useUiStore((state) => state.sidebarCollapsed);
  const mobileOpen = useUiStore((state) => state.mobileNavOpen);
  const setMobileOpen = useUiStore((state) => state.setMobileNavOpen);
  const toggleSidebar = useUiStore((state) => state.toggleSidebar);
  const theme = useUiStore((state) => state.theme);
  const setTheme = useUiStore((state) => state.setTheme);
  const ready = useQuery({ queryKey: ["ready"], queryFn: api.ready, refetchInterval: 15_000 });
  const runtimeStatus = ready.data?.status === "ok" ? "ready" : ready.isError ? "not_ready" : "connecting";
  return <div className="min-h-screen bg-canvas text-ink">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-line bg-panel transition-transform duration-200 lg:translate-x-0 ${collapsed ? "lg:w-[72px]" : ""} ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-16 items-center justify-between border-b border-line px-4">
        <Link to="/" className="flex items-center gap-3 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400/80" onClick={() => setMobileOpen(false)}>
          <span className="grid h-8 w-8 place-items-center rounded-md bg-ink text-sm font-black tracking-[-0.1em] text-amber-300">M·</span>
          {!collapsed ? <span><span className="block text-sm font-bold tracking-tight">Mnemos</span><span className="block text-[10px] uppercase tracking-[0.2em] text-ink-muted">Runtime console</span></span> : null}
        </Link>
        <button type="button" aria-label="Close navigation" onClick={() => setMobileOpen(false)} className="rounded-md p-2 text-ink-muted hover:bg-ink/5 lg:hidden"><X size={18} /></button>
      </div>
      <nav aria-label="Primary" className="flex-1 space-y-1 px-3 py-5">
        <NavItem to="/" label="Overview" icon={<LayoutDashboard size={17} />} collapsed={collapsed} onNavigate={() => setMobileOpen(false)} />
        <NavItem to="/sessions" label="Sessions" icon={<Database size={17} />} collapsed={collapsed} onNavigate={() => setMobileOpen(false)} />
        <NavItem to="/events" label="Events" icon={<Radio size={17} />} collapsed={collapsed} onNavigate={() => setMobileOpen(false)} />
        <div className={`pb-2 pt-8 ${collapsed ? "hidden" : ""}`}><Label>Coming later</Label></div>
        <FutureItem label="Memory" collapsed={collapsed} />
        <FutureItem label="Artifacts" collapsed={collapsed} />
        <FutureItem label="Tools & PTC" collapsed={collapsed} />
        <FutureItem label="Agents & Tasks" collapsed={collapsed} />
      </nav>
      <div className="border-t border-line p-3">
        <NavItem to="/settings" label="Settings" icon={<Settings size={17} />} collapsed={collapsed} onNavigate={() => setMobileOpen(false)} />
        {!collapsed ? <div className="mt-3 rounded-lg bg-canvas px-3 py-3"><div className="flex items-center gap-2"><StatusDot status={runtimeStatus === "ready" ? "ready" : runtimeStatus === "not_ready" ? "not_ready" : "reconnecting"} /><span className="text-xs font-semibold">{runtimeStatus === "ready" ? "Runtime ready" : runtimeStatus === "not_ready" ? "Runtime unavailable" : "Connecting"}</span></div><p className="mt-1 text-[11px] text-ink-muted">Observer mode · F1</p></div> : null}
      </div>
    </aside>
    {mobileOpen ? <button type="button" aria-label="Close navigation overlay" className="fixed inset-0 z-20 bg-black/30 lg:hidden" onClick={() => setMobileOpen(false)} /> : null}
    <div className={`min-h-screen transition-[padding] duration-200 ${collapsed ? "lg:pl-[72px]" : "lg:pl-64"}`}>
      <header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-line bg-canvas/90 px-4 backdrop-blur sm:px-6">
        <div className="flex items-center gap-2"><button type="button" className="rounded-md p-2 text-ink-muted hover:bg-ink/5 lg:hidden" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu size={19} /></button><button type="button" className="hidden rounded-md p-2 text-ink-muted hover:bg-ink/5 lg:inline-flex" aria-label="Toggle sidebar" onClick={toggleSidebar}><PanelLeft size={18} /></button><span className="hidden text-xs text-ink-muted sm:inline">Cognitive runtime / local observer</span></div>
        <div className="flex items-center gap-3"><div className="flex items-center gap-2 text-xs text-ink-muted"><StatusDot status={runtimeStatus === "ready" ? "ready" : runtimeStatus === "not_ready" ? "not_ready" : "reconnecting"} />{runtimeStatus === "ready" ? "Ready" : runtimeStatus === "not_ready" ? "Offline" : "Connecting"}</div><ThemeToggle theme={theme} setTheme={setTheme} /></div>
      </header>
      <main className="mx-auto max-w-[1440px] px-4 py-6 sm:px-6 lg:px-8"><Outlet /></main>
    </div>
  </div>;
}

function NavItem({ to, label, icon, collapsed, onNavigate }: { to: string; label: string; icon: JSX.Element; collapsed: boolean; onNavigate: () => void }): JSX.Element { return <Link to={to} activeOptions={{ exact: to === "/" }} activeProps={{ className: "bg-ink text-white shadow-sm dark:bg-white dark:text-ink" }} inactiveProps={{ className: "text-ink-muted hover:bg-ink/5 hover:text-ink dark:hover:bg-white/8" }} className={`group flex min-h-10 items-center gap-3 rounded-md px-3 text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400/80 ${collapsed ? "justify-center px-2" : ""}`} title={collapsed ? label : undefined} onClick={onNavigate}>{icon}{collapsed ? <span className="sr-only">{label}</span> : <span>{label}</span>}</Link>; }
function FutureItem({ label, collapsed }: { label: string; collapsed: boolean }): JSX.Element { return <div aria-disabled="true" title={collapsed ? `${label} — coming later` : undefined} className={`flex min-h-10 items-center gap-3 rounded-md px-3 text-sm font-semibold text-ink-muted/45 ${collapsed ? "justify-center px-2" : ""}`}><CircleHelp size={17} /><span className={collapsed ? "sr-only" : ""}>{label}</span>{!collapsed ? <Badge>F2+</Badge> : null}</div>; }
function ThemeToggle({ theme, setTheme }: { theme: ThemePreference; setTheme: (theme: ThemePreference) => void }): JSX.Element { const next: Record<ThemePreference, ThemePreference> = { system: "dark", dark: "light", light: "system" }; return <button type="button" aria-label={`Theme: ${theme}. Switch theme`} title={`Theme: ${theme}`} onClick={() => setTheme(next[theme])} className="rounded-md p-2 text-ink-muted hover:bg-ink/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400/80">{theme === "light" ? <Sun size={17} /> : theme === "dark" ? <Moon size={17} /> : <span className="text-xs font-bold">SYS</span>}</button>; }

export function OverviewPage(): JSX.Element {
  const summary = useQuery({ queryKey: ["summary"], queryFn: api.summary, refetchInterval: 15_000 });
  const ready = useQuery({ queryKey: ["ready"], queryFn: api.ready, refetchInterval: 15_000 });
  const sessions = useQuery({ queryKey: ["sessions", { limit: 5 }], queryFn: () => api.sessions({ limit: 5 }) });
  const events = useLiveEvents(8);
  return <div className="space-y-6">
    <PageIntro eyebrow="Runtime / overview" title="A live view of your cognitive runtime." detail="Observe the working set, long-term substrate, and agent activity without taking ownership of the runtime itself." />
    {summary.isError ? <ErrorState message="Runtime summary unavailable. Check the server connection." onRetry={() => void summary.refetch()} /> : null}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard label="Runtime status" value={summary.data?.status ?? "Loading"} detail={summary.data?.version ?? ""} tone={summary.data?.status === "ready" ? "success" : "warning"} />
      <StatCard label="Sessions" value={formatNumber(summary.data?.sessionsCount)} detail={`${formatNumber(summary.data?.activeSessions)} active`} />
      <StatCard label="Agents" value={formatNumber(summary.data?.activeAgents)} detail={`${formatNumber(summary.data?.registeredAgents)} registered`} />
      <StatCard label="Context limit" value={summary.data?.contextLimitTokens ? `${Math.round(summary.data.contextLimitTokens / 1024)}k` : "N/A"} detail="visible agent" />
    </div>
    <div className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]">
      <Card><CardHeader><div className="flex items-center justify-between"><div><Label>Runtime posture</Label><h2 className="mt-1 text-lg font-semibold tracking-tight">Ready to observe</h2></div><StatusBadge status={summary.data?.status ?? "loading"} /></div></CardHeader><CardBody><div className="grid gap-4 sm:grid-cols-2"><RuntimeMetric icon={<Cpu size={17} />} label="Sandbox" value={summary.data?.sandboxBackend ?? "N/A"} detail={summary.data?.sandboxStatus ?? "No data"} /><RuntimeMetric icon={<Database size={17} />} label="Readiness" value={ready.data?.status === "ok" ? "All checks clear" : ready.isLoading ? "Checking" : "Review checks"} detail={`${ready.data?.checks.length ?? 0} dependency checks`} /><RuntimeMetric icon={<Activity size={17} />} label="Queue" value={summary.data?.queuedJobs === undefined ? "N/A" : formatNumber(summary.data.queuedJobs)} detail="queued jobs" /><RuntimeMetric icon={<Search size={17} />} label="Memory" value={summary.data?.memoryCount === undefined ? "N/A" : formatNumber(summary.data.memoryCount)} detail="derived records" /></div></CardBody></Card>
      <Card><CardHeader><div className="flex items-center justify-between"><div><Label>Recent activity</Label><h2 className="mt-1 text-lg font-semibold tracking-tight">Runtime pulse</h2></div><Link className="text-xs font-semibold text-amber-600 hover:text-amber-500" to="/events">Open stream <ChevronRight className="inline" size={14} /></Link></div></CardHeader><CardBody className="p-0">{events.events.length === 0 ? <div className="px-5 py-10 text-sm text-ink-muted">No live events yet. The stream is standing by.</div> : <div className="divide-y divide-line">{events.events.slice(0, 5).map((event) => <EventRow key={event.id} event={event} />)}</div>}</CardBody></Card>
    </div>
    <Card><CardHeader><div className="flex items-center justify-between"><div><Label>Sessions</Label><h2 className="mt-1 text-lg font-semibold tracking-tight">Recent working sets</h2></div><Link className="text-xs font-semibold text-amber-600 hover:text-amber-500" to="/sessions">View all <ChevronRight className="inline" size={14} /></Link></div></CardHeader><CardBody className="p-0">{sessions.isLoading ? <div className="space-y-3 px-5 py-5"><Skeleton className="h-10" /><Skeleton className="h-10" /></div> : sessions.data?.items.length ? <div className="divide-y divide-line">{sessions.data.items.map((session) => <SessionRow key={session.id} session={session} />)}</div> : <div className="p-5"><EmptyState title="No sessions yet" detail="Create a test session to give the console something to observe." /></div>}</CardBody></Card>
  </div>;
}

export function SessionsPage(): JSX.Element { const sessions = useQuery({ queryKey: ["sessions", { limit: 50 }], queryFn: () => api.sessions({ limit: 50 }) }); return <div className="space-y-6"><PageIntro eyebrow="Runtime / sessions" title="Working sets, not transcripts." detail="Sessions are the current handles into canonical History. F1 keeps this view read-only." />{sessions.isLoading ? <div className="space-y-3"><Skeleton className="h-16" /><Skeleton className="h-16" /><Skeleton className="h-16" /></div> : sessions.isError ? <ErrorState message="Sessions could not be loaded." onRetry={() => void sessions.refetch()} /> : sessions.data?.items.length ? <Card><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-line bg-canvas/60 text-[11px] uppercase tracking-[0.13em] text-ink-muted"><tr><th className="px-5 py-3 font-semibold">Session</th><th className="px-5 py-3 font-semibold">Status</th><th className="px-5 py-3 font-semibold">Messages</th><th className="px-5 py-3 font-semibold">Updated</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-line">{sessions.data.items.map((session) => <tr key={session.id} className="group hover:bg-ink/[0.025] dark:hover:bg-white/[0.025]"><td className="px-5 py-4"><Link to="/sessions/$sessionId" params={{ sessionId: session.id }} className="block font-semibold hover:text-amber-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400/80"><span className="block">{session.displayName ?? "Untitled session"}</span><CopyableId value={session.id} /></Link></td><td className="px-5 py-4"><StatusBadge status={session.status} /></td><td className="px-5 py-4 font-mono text-xs text-ink-muted">{formatNumber(session.messageCount)}</td><td className="px-5 py-4 text-ink-muted">{formatRelative(session.updatedAt)}</td><td className="px-5 py-4 text-right"><Link to="/sessions/$sessionId" params={{ sessionId: session.id }} className="text-ink-muted opacity-0 transition-opacity group-hover:opacity-100 focus:opacity-100"><ExternalLink size={16} aria-label="Open session" /></Link></td></tr>)}</tbody></table></div></Card> : <EmptyState title="No sessions yet" detail="The runtime has no visible working sets." />}</div>; }

function SessionPage(): JSX.Element { const { sessionId } = useParams({ from: "/sessions/$sessionId" }); const session = useQuery({ queryKey: ["session", sessionId], queryFn: () => api.session(sessionId) }); return <div className="space-y-6">{session.isLoading ? <><Skeleton className="h-8 w-64" /><Skeleton className="h-40" /></> : session.isError ? <ErrorState message={session.error instanceof ApiClientError && session.error.code === "not_found" ? "Session not found." : "Session details unavailable."} onRetry={() => void session.refetch()} /> : session.data ? <><div><Link to="/sessions" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-ink-muted hover:text-ink"><ArrowLeft size={15} />Sessions</Link><PageIntro eyebrow="Session / read-only foundation" title={session.data.displayName ?? "Untitled session"} detail={<span className="font-mono text-xs">{session.data.id}</span>} /></div><div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><Card><CardHeader><Label>Session metadata</Label></CardHeader><CardBody><dl className="space-y-4 text-sm"><Definition label="Status" value={<StatusBadge status={session.data.status} />} /><Definition label="Messages" value={formatNumber(session.data.messageCount)} /><Definition label="Created" value={formatDate(session.data.createdAt)} /><Definition label="Updated" value={formatDate(session.data.updatedAt)} /><Definition label="Agents" value={session.data.activeAgentIds?.length ? session.data.activeAgentIds.join(", ") : "N/A"} /></dl></CardBody></Card><Card><CardHeader><div className="flex items-center justify-between"><div><Label>Recent messages</Label><h2 className="mt-1 text-lg font-semibold">A bounded glimpse</h2></div><Badge>F2 · chat pending</Badge></div></CardHeader><CardBody className="space-y-3">{session.data.recentMessages.length ? session.data.recentMessages.map((message) => <div key={message.id} className="rounded-lg border border-line bg-canvas/60 px-4 py-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-ink-muted">{message.role}</span><span className="text-xs text-ink-muted">{formatRelative(message.createdAt)}</span></div><p className="mt-2 text-sm leading-6">{message.preview}</p></div>) : <EmptyState title="No recent messages" detail="This session has no public message previews." />}</CardBody></Card></div></> : null}</div>; }

export function EventsPage(): JSX.Element { const filter = useUiStore((state) => state.eventFilter); const paused = useUiStore((state) => state.eventsPaused); const setFilter = useUiStore((state) => state.setEventFilter); const setPaused = useUiStore((state) => state.setEventsPaused); const events = useLiveEvents(500, paused); const filtered = filter === "all" ? events.events : events.events.filter((event) => event.type === filter); const eventTypes = [...new Set(events.events.map((event) => event.type))]; return <div className="space-y-6"><PageIntro eyebrow="Runtime / events" title="The runtime pulse, safely summarized." detail="This is a bounded live debug buffer, not the canonical audit log. Internal prompts and payloads stay on the server." /><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><StatusDot status={events.status} /><span className="text-sm font-semibold capitalize">{events.status === "live" ? "Live" : events.status === "reconnecting" ? "Reconnecting" : "Disconnected"}</span>{paused ? <Badge tone="warning">UI paused</Badge> : null}{events.pending > 0 ? <span className="text-xs text-ink-muted">{events.pending} buffered</span> : null}</div><div className="flex flex-wrap items-center gap-2"><label className="sr-only" htmlFor="event-filter">Filter events</label><select id="event-filter" value={filter} onChange={(event) => setFilter(event.target.value)} className="h-9 rounded-md border border-line bg-panel px-3 text-sm focus:outline-none focus:ring-2 focus:ring-amber-400/80"><option value="all">All event types</option>{eventTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select><Button variant="outline" onClick={() => setPaused(!paused)}>{paused ? "Resume" : "Pause"}</Button><Button variant="quiet" onClick={events.clear}>Clear</Button></div></div></CardHeader><CardBody className="p-0">{filtered.length === 0 ? <div className="px-5 py-12"><EmptyState title="No events in this view" detail="Keep the stream open while the runtime changes." /></div> : <div className="max-h-[620px] overflow-auto">{filtered.map((event) => <EventRow key={event.id} event={event} detailed />)}</div>}</CardBody><div className="border-t border-line px-5 py-3 text-xs text-ink-muted">Showing {filtered.length} of {events.events.length} buffered events · capped at 500</div></Card></div>; }

function SettingsPage(): JSX.Element { const meta = useQuery({ queryKey: ["meta"], queryFn: api.meta }); const summary = useQuery({ queryKey: ["summary"], queryFn: api.summary }); return <div className="space-y-6"><PageIntro eyebrow="Runtime / settings" title="Read-only configuration summary." detail="Operational controls stay outside the Console in F1. Secrets and raw environment values are never exposed here." /><Card><CardBody><dl className="grid gap-x-8 gap-y-5 sm:grid-cols-2"><Definition label="Profile" value={summary.data?.profile ?? "N/A"} /><Definition label="API version" value={meta.data?.apiVersion ?? "N/A"} /><Definition label="Runtime version" value={meta.data?.version ?? "N/A"} /><Definition label="Schema version" value={meta.data?.schemaVersion ?? "N/A"} /><Definition label="Context default" value={summary.data?.contextLimitTokens ? `${formatNumber(summary.data.contextLimitTokens)} tokens` : "N/A"} /><Definition label="Sandbox backend" value={summary.data?.sandboxBackend ?? "N/A"} /><Definition label="Artifact quota" value="Not exposed" /><Definition label="Database path" value="Hidden" /></dl></CardBody></Card><Card className="border-dashed"><CardBody><div className="flex items-start gap-3"><CircleHelp className="mt-0.5 text-amber-500" size={18} /><div><p className="text-sm font-semibold">F1 is intentionally observer-first.</p><p className="mt-1 text-sm leading-6 text-ink-muted">Chat Workbench, Context Inspector, Artifact and Tool views, and the Multi-Agent graph arrive in later frontend phases.</p></div></div></CardBody></Card></div>; }

function PageIntro({ eyebrow, title, detail }: { eyebrow: string; title: string; detail: React.ReactNode }): JSX.Element { return <div className="max-w-3xl"><Label>{eyebrow}</Label><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-muted sm:text-base">{detail}</p></div>; }
function StatCard({ label, value, detail, tone = "neutral" }: { label: string; value: string; detail: string; tone?: "neutral" | "success" | "warning" }): JSX.Element { return <Card className="overflow-hidden"><CardBody className="relative"><div className={`absolute inset-x-0 top-0 h-0.5 ${tone === "success" ? "bg-emerald-400" : tone === "warning" ? "bg-amber-400" : "bg-ink/10 dark:bg-white/15"}`} /><Label>{label}</Label><p className="mt-3 truncate text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-ink-muted">{detail}</p></CardBody></Card>; }
function RuntimeMetric({ icon, label, value, detail }: { icon: JSX.Element; label: string; value: string; detail: string }): JSX.Element { return <div className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-md bg-amber-400/15 text-amber-600">{icon}</span><div className="min-w-0"><p className="text-sm font-semibold truncate">{value}</p><p className="mt-0.5 text-xs text-ink-muted">{label} · {detail}</p></div></div>; }
function SessionRow({ session }: { session: import("@mnemos/contracts").SessionSummaryDto }): JSX.Element { return <Link to="/sessions/$sessionId" params={{ sessionId: session.id }} className="flex items-center justify-between gap-4 px-5 py-4 transition-colors hover:bg-ink/[0.025] dark:hover:bg-white/[0.025] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-amber-400/80"><div className="min-w-0"><p className="truncate text-sm font-semibold">{session.displayName ?? "Untitled session"}</p><div className="mt-1 flex items-center gap-2"><CopyableId value={session.id} /><span className="text-xs text-ink-muted">{formatNumber(session.messageCount)} messages</span></div></div><div className="flex shrink-0 items-center gap-3"><span className="hidden text-xs text-ink-muted sm:inline">{formatRelative(session.updatedAt)}</span><StatusBadge status={session.status} /></div></Link>; }
function EventRow({ event, detailed = false }: { event: RuntimeEventDto; detailed?: boolean }): JSX.Element { return <div className={`flex gap-3 px-5 py-3 ${detailed ? "border-b border-line last:border-b-0" : ""}`}><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-amber-400" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="font-mono text-xs font-semibold text-ink">{event.type}</span>{event.sessionId ? <CopyableId value={event.sessionId} /> : null}<span className="text-[11px] text-ink-muted">{formatRelative(event.timestamp)}</span></div>{detailed ? <pre className="mt-2 max-w-full overflow-x-auto rounded-md bg-canvas p-3 font-mono text-[11px] leading-5 text-ink-muted">{JSON.stringify(event.payload, null, 2)}</pre> : null}</div></div>; }
function Definition({ label, value }: { label: string; value: React.ReactNode }): JSX.Element { return <div><dt className="text-xs text-ink-muted">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>; }
function NotFoundPage(): JSX.Element { const navigate = useNavigate(); return <div className="mx-auto max-w-xl py-20 text-center"><Label>404 / route not found</Label><h1 className="mt-3 text-3xl font-semibold">This page is not part of F1.</h1><p className="mt-3 text-sm leading-6 text-ink-muted">The console keeps future surfaces out of the navigation until their runtime contracts are ready.</p><Button className="mt-6" onClick={() => void navigate({ to: "/" })}>Back to overview</Button></div>; }

function useLiveEvents(limit: number, paused = false): { events: RuntimeEventDto[]; status: "live" | "reconnecting" | "disconnected"; pending: number; clear: () => void } {
  const [events, setEvents] = React.useState<RuntimeEventDto[]>([]);
  const [status, setStatus] = React.useState<"live" | "reconnecting" | "disconnected">("reconnecting");
  const pendingRef = React.useRef<RuntimeEventDto[]>([]);
  const pausedRef = React.useRef(paused);
  React.useEffect(() => { pausedRef.current = paused; if (!paused && pendingRef.current.length) { setEvents((current) => [...pendingRef.current.splice(0), ...current].slice(0, limit)); } }, [paused, limit]);
  React.useEffect(() => { const cleanup = subscribeToEvents((event) => { if (pausedRef.current) { pendingRef.current = [event, ...pendingRef.current].slice(0, limit); return; } setEvents((current) => [event, ...current].slice(0, limit)); }, setStatus); return cleanup; }, [limit]);
  return { events, status, pending: pendingRef.current.length, clear: () => { setEvents([]); pendingRef.current = []; } };
}
